/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as HelpRouteImport } from './routes/help'
import { Route as IjpRouteImport } from './routes/ijp'
import { Route as InboxRouteImport } from './routes/inbox'
import { Route as IntegrationsRouteImport } from './routes/integrations'
import { Route as InterviewsRouteImport } from './routes/interviews'
import { Route as MastersRouteImport } from './routes/masters'
import { Route as MatchingRouteImport } from './routes/matching'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as OrganisationRouteImport } from './routes/organisation'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as TeamRouteImport } from './routes/team'
import { Route as ApplyIdRouteImport } from './routes/apply.$id'
import { Route as AssessTokenRouteImport } from './routes/assess.$token'
import { Route as CandidatesIndexRouteImport } from './routes/candidates.index'
import { Route as CandidatesIdRouteImport } from './routes/candidates.$id'
import { Route as InterviewsMineRouteImport } from './routes/interviews.mine'
import { Route as RequisitionsIndexRouteImport } from './routes/requisitions.index'
import { Route as RequisitionsIdRouteImport } from './routes/requisitions.$id'
import { Route as ApiPublicCaptureRouteImport } from './routes/api/public/capture'
import { Route as ApiPublicInboundEmailRouteImport } from './routes/api/public/inbound-email'
import { Route as ApiPublicInboxSyncRouteImport } from './routes/api/public/inbox-sync'
import { Route as ApiPublicSyncCandidatesRouteImport } from './routes/api/public/sync-candidates'
import { Route as ApiPublicLinkedinCallbackRouteImport } from './routes/api/public/linkedin/callback'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const IjpRoute = IjpRouteImport.update({
  id: '/ijp',
  path: '/ijp',
  getParentRoute: () => rootRouteImport,
} as any)
const InboxRoute = InboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => rootRouteImport,
} as any)
const IntegrationsRoute = IntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsRoute = InterviewsRouteImport.update({
  id: '/interviews',
  path: '/interviews',
  getParentRoute: () => rootRouteImport,
} as any)
const MastersRoute = MastersRouteImport.update({
  id: '/masters',
  path: '/masters',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchingRoute = MatchingRouteImport.update({
  id: '/matching',
  path: '/matching',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganisationRoute = OrganisationRouteImport.update({
  id: '/organisation',
  path: '/organisation',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyIdRoute = ApplyIdRouteImport.update({
  id: '/apply/$id',
  path: '/apply/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessTokenRoute = AssessTokenRouteImport.update({
  id: '/assess/$token',
  path: '/assess/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIndexRoute = CandidatesIndexRouteImport.update({
  id: '/candidates/',
  path: '/candidates/',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidatesIdRoute = CandidatesIdRouteImport.update({
  id: '/candidates/$id',
  path: '/candidates/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewsMineRoute = InterviewsMineRouteImport.update({
  id: '/mine',
  path: '/mine',
  getParentRoute: () => InterviewsRoute,
} as any)
const RequisitionsIndexRoute = RequisitionsIndexRouteImport.update({
  id: '/requisitions/',
  path: '/requisitions/',
  getParentRoute: () => rootRouteImport,
} as any)
const RequisitionsIdRoute = RequisitionsIdRouteImport.update({
  id: '/requisitions/$id',
  path: '/requisitions/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCaptureRoute = ApiPublicCaptureRouteImport.update({
  id: '/api/public/capture',
  path: '/api/public/capture',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInboundEmailRoute = ApiPublicInboundEmailRouteImport.update({
  id: '/api/public/inbound-email',
  path: '/api/public/inbound-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInboxSyncRoute = ApiPublicInboxSyncRouteImport.update({
  id: '/api/public/inbox-sync',
  path: '/api/public/inbox-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncCandidatesRoute = ApiPublicSyncCandidatesRouteImport.update({
  id: '/api/public/sync-candidates',
  path: '/api/public/sync-candidates',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicLinkedinCallbackRoute =
  ApiPublicLinkedinCallbackRouteImport.update({
    id: '/api/public/linkedin/callback',
    path: '/api/public/linkedin/callback',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/help': typeof HelpRoute
  '/ijp': typeof IjpRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/interviews': typeof InterviewsRouteWithChildren
  '/masters': typeof MastersRoute
  '/matching': typeof MatchingRoute
  '/offers': typeof OffersRoute
  '/organisation': typeof OrganisationRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/team': typeof TeamRoute
  '/apply/$id': typeof ApplyIdRoute
  '/assess/$token': typeof AssessTokenRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/interviews/mine': typeof InterviewsMineRoute
  '/requisitions/$id': typeof RequisitionsIdRoute
  '/candidates/': typeof CandidatesIndexRoute
  '/requisitions/': typeof RequisitionsIndexRoute
  '/api/public/capture': typeof ApiPublicCaptureRoute
  '/api/public/inbound-email': typeof ApiPublicInboundEmailRoute
  '/api/public/inbox-sync': typeof ApiPublicInboxSyncRoute
  '/api/public/sync-candidates': typeof ApiPublicSyncCandidatesRoute
  '/api/public/linkedin/callback': typeof ApiPublicLinkedinCallbackRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/help': typeof HelpRoute
  '/ijp': typeof IjpRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/interviews': typeof InterviewsRouteWithChildren
  '/masters': typeof MastersRoute
  '/matching': typeof MatchingRoute
  '/offers': typeof OffersRoute
  '/organisation': typeof OrganisationRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/team': typeof TeamRoute
  '/apply/$id': typeof ApplyIdRoute
  '/assess/$token': typeof AssessTokenRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/interviews/mine': typeof InterviewsMineRoute
  '/requisitions/$id': typeof RequisitionsIdRoute
  '/candidates': typeof CandidatesIndexRoute
  '/requisitions': typeof RequisitionsIndexRoute
  '/api/public/capture': typeof ApiPublicCaptureRoute
  '/api/public/inbound-email': typeof ApiPublicInboundEmailRoute
  '/api/public/inbox-sync': typeof ApiPublicInboxSyncRoute
  '/api/public/sync-candidates': typeof ApiPublicSyncCandidatesRoute
  '/api/public/linkedin/callback': typeof ApiPublicLinkedinCallbackRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/help': typeof HelpRoute
  '/ijp': typeof IjpRoute
  '/inbox': typeof InboxRoute
  '/integrations': typeof IntegrationsRoute
  '/interviews': typeof InterviewsRouteWithChildren
  '/masters': typeof MastersRoute
  '/matching': typeof MatchingRoute
  '/offers': typeof OffersRoute
  '/organisation': typeof OrganisationRoute
  '/platform': typeof PlatformRoute
  '/privacy': typeof PrivacyRoute
  '/reports': typeof ReportsRoute
  '/team': typeof TeamRoute
  '/apply/$id': typeof ApplyIdRoute
  '/assess/$token': typeof AssessTokenRoute
  '/candidates/$id': typeof CandidatesIdRoute
  '/interviews/mine': typeof InterviewsMineRoute
  '/requisitions/$id': typeof RequisitionsIdRoute
  '/candidates/': typeof CandidatesIndexRoute
  '/requisitions/': typeof RequisitionsIndexRoute
  '/api/public/capture': typeof ApiPublicCaptureRoute
  '/api/public/inbound-email': typeof ApiPublicInboundEmailRoute
  '/api/public/inbox-sync': typeof ApiPublicInboxSyncRoute
  '/api/public/sync-candidates': typeof ApiPublicSyncCandidatesRoute
  '/api/public/linkedin/callback': typeof ApiPublicLinkedinCallbackRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/help'
    | '/ijp'
    | '/inbox'
    | '/integrations'
    | '/interviews'
    | '/masters'
    | '/matching'
    | '/offers'
    | '/organisation'
    | '/platform'
    | '/privacy'
    | '/reports'
    | '/team'
    | '/apply/$id'
    | '/assess/$token'
    | '/candidates/$id'
    | '/interviews/mine'
    | '/requisitions/$id'
    | '/candidates/'
    | '/requisitions/'
    | '/api/public/capture'
    | '/api/public/inbound-email'
    | '/api/public/inbox-sync'
    | '/api/public/sync-candidates'
    | '/api/public/linkedin/callback'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/help'
    | '/ijp'
    | '/inbox'
    | '/integrations'
    | '/interviews'
    | '/masters'
    | '/matching'
    | '/offers'
    | '/organisation'
    | '/platform'
    | '/privacy'
    | '/reports'
    | '/team'
    | '/apply/$id'
    | '/assess/$token'
    | '/candidates/$id'
    | '/interviews/mine'
    | '/requisitions/$id'
    | '/candidates'
    | '/requisitions'
    | '/api/public/capture'
    | '/api/public/inbound-email'
    | '/api/public/inbox-sync'
    | '/api/public/sync-candidates'
    | '/api/public/linkedin/callback'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/cookies'
    | '/help'
    | '/ijp'
    | '/inbox'
    | '/integrations'
    | '/interviews'
    | '/masters'
    | '/matching'
    | '/offers'
    | '/organisation'
    | '/platform'
    | '/privacy'
    | '/reports'
    | '/team'
    | '/apply/$id'
    | '/assess/$token'
    | '/candidates/$id'
    | '/interviews/mine'
    | '/requisitions/$id'
    | '/candidates/'
    | '/requisitions/'
    | '/api/public/capture'
    | '/api/public/inbound-email'
    | '/api/public/inbox-sync'
    | '/api/public/sync-candidates'
    | '/api/public/linkedin/callback'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CookiesRoute: typeof CookiesRoute
  HelpRoute: typeof HelpRoute
  IjpRoute: typeof IjpRoute
  InboxRoute: typeof InboxRoute
  IntegrationsRoute: typeof IntegrationsRoute
  InterviewsRoute: typeof InterviewsRouteWithChildren
  MastersRoute: typeof MastersRoute
  MatchingRoute: typeof MatchingRoute
  OffersRoute: typeof OffersRoute
  OrganisationRoute: typeof OrganisationRoute
  PlatformRoute: typeof PlatformRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportsRoute: typeof ReportsRoute
  TeamRoute: typeof TeamRoute
  ApplyIdRoute: typeof ApplyIdRoute
  AssessTokenRoute: typeof AssessTokenRoute
  CandidatesIdRoute: typeof CandidatesIdRoute
  RequisitionsIdRoute: typeof RequisitionsIdRoute
  CandidatesIndexRoute: typeof CandidatesIndexRoute
  RequisitionsIndexRoute: typeof RequisitionsIndexRoute
  ApiPublicCaptureRoute: typeof ApiPublicCaptureRoute
  ApiPublicInboundEmailRoute: typeof ApiPublicInboundEmailRoute
  ApiPublicInboxSyncRoute: typeof ApiPublicInboxSyncRoute
  ApiPublicSyncCandidatesRoute: typeof ApiPublicSyncCandidatesRoute
  ApiPublicLinkedinCallbackRoute: typeof ApiPublicLinkedinCallbackRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ijp': {
      id: '/ijp'
      path: '/ijp'
      fullPath: '/ijp'
      preLoaderRoute: typeof IjpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inbox': {
      id: '/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof InboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/integrations': {
      id: '/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof IntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews': {
      id: '/interviews'
      path: '/interviews'
      fullPath: '/interviews'
      preLoaderRoute: typeof InterviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/masters': {
      id: '/masters'
      path: '/masters'
      fullPath: '/masters'
      preLoaderRoute: typeof MastersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/matching': {
      id: '/matching'
      path: '/matching'
      fullPath: '/matching'
      preLoaderRoute: typeof MatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organisation': {
      id: '/organisation'
      path: '/organisation'
      fullPath: '/organisation'
      preLoaderRoute: typeof OrganisationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/$id': {
      id: '/apply/$id'
      path: '/apply/$id'
      fullPath: '/apply/$id'
      preLoaderRoute: typeof ApplyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assess/$token': {
      id: '/assess/$token'
      path: '/assess/$token'
      fullPath: '/assess/$token'
      preLoaderRoute: typeof AssessTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/': {
      id: '/candidates/'
      path: '/candidates'
      fullPath: '/candidates/'
      preLoaderRoute: typeof CandidatesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidates/$id': {
      id: '/candidates/$id'
      path: '/candidates/$id'
      fullPath: '/candidates/$id'
      preLoaderRoute: typeof CandidatesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interviews/mine': {
      id: '/interviews/mine'
      path: '/mine'
      fullPath: '/interviews/mine'
      preLoaderRoute: typeof InterviewsMineRouteImport
      parentRoute: typeof InterviewsRoute
    }
    '/requisitions/': {
      id: '/requisitions/'
      path: '/requisitions'
      fullPath: '/requisitions/'
      preLoaderRoute: typeof RequisitionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requisitions/$id': {
      id: '/requisitions/$id'
      path: '/requisitions/$id'
      fullPath: '/requisitions/$id'
      preLoaderRoute: typeof RequisitionsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/capture': {
      id: '/api/public/capture'
      path: '/api/public/capture'
      fullPath: '/api/public/capture'
      preLoaderRoute: typeof ApiPublicCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inbound-email': {
      id: '/api/public/inbound-email'
      path: '/api/public/inbound-email'
      fullPath: '/api/public/inbound-email'
      preLoaderRoute: typeof ApiPublicInboundEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inbox-sync': {
      id: '/api/public/inbox-sync'
      path: '/api/public/inbox-sync'
      fullPath: '/api/public/inbox-sync'
      preLoaderRoute: typeof ApiPublicInboxSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync-candidates': {
      id: '/api/public/sync-candidates'
      path: '/api/public/sync-candidates'
      fullPath: '/api/public/sync-candidates'
      preLoaderRoute: typeof ApiPublicSyncCandidatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/linkedin/callback': {
      id: '/api/public/linkedin/callback'
      path: '/api/public/linkedin/callback'
      fullPath: '/api/public/linkedin/callback'
      preLoaderRoute: typeof ApiPublicLinkedinCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InterviewsRouteChildren {
  InterviewsMineRoute: typeof InterviewsMineRoute
}

const InterviewsRouteChildren: InterviewsRouteChildren = {
  InterviewsMineRoute: InterviewsMineRoute,
}

const InterviewsRouteWithChildren = InterviewsRoute._addFileChildren(
  InterviewsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CookiesRoute: CookiesRoute,
  HelpRoute: HelpRoute,
  IjpRoute: IjpRoute,
  InboxRoute: InboxRoute,
  IntegrationsRoute: IntegrationsRoute,
  InterviewsRoute: InterviewsRouteWithChildren,
  MastersRoute: MastersRoute,
  MatchingRoute: MatchingRoute,
  OffersRoute: OffersRoute,
  OrganisationRoute: OrganisationRoute,
  PlatformRoute: PlatformRoute,
  PrivacyRoute: PrivacyRoute,
  ReportsRoute: ReportsRoute,
  TeamRoute: TeamRoute,
  ApplyIdRoute: ApplyIdRoute,
  AssessTokenRoute: AssessTokenRoute,
  CandidatesIdRoute: CandidatesIdRoute,
  RequisitionsIdRoute: RequisitionsIdRoute,
  CandidatesIndexRoute: CandidatesIndexRoute,
  RequisitionsIndexRoute: RequisitionsIndexRoute,
  ApiPublicCaptureRoute: ApiPublicCaptureRoute,
  ApiPublicInboundEmailRoute: ApiPublicInboundEmailRoute,
  ApiPublicInboxSyncRoute: ApiPublicInboxSyncRoute,
  ApiPublicSyncCandidatesRoute: ApiPublicSyncCandidatesRoute,
  ApiPublicLinkedinCallbackRoute: ApiPublicLinkedinCallbackRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
